# Generated by Django 5.0.6 on 2024-05-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_impacts', '0003_rename_name_impact_impact_impact_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='impact',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='impact',
            name='impact',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='impact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='impact',
            name='device',
        ),
        migrations.RemoveField(
            model_name='impact',
            name='vm',
        ),
    ]
