# Generated by Django 5.0.6 on 2024-06-03 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_impacts', '0004_alter_impact_unique_together_alter_impact_impact_and_more'),
        ('ipam', '0069_gfk_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewImpactIPAddress',
            fields=[
                ('impact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('impact', models.TextField()),
                ('redundancy', models.BooleanField()),
                ('ip_address', models.CharField(max_length=15)),
                ('vrf', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'view_impact_ipaddress',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='impact',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipaddress', to='ipam.ipaddress'),
        ),
    ]
