# Generated by Django 5.0.6 on 2024-06-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_impacts', '0005_viewimpactipaddress_alter_impact_ip_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewImpactIPAddress',
        ),
    ]
